# Generated by Django 6.0 on 2025-12-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cetegory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cetegory_name',
            new_name='category_name',
        ),
    ]
