# Generated by Django 6.0 on 2026-01-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.RenameField(
            model_name='about',
            old_name='About_heading',
            new_name='about_heading',
        ),
        migrations.RemoveField(
            model_name='about',
            name='About_description',
        ),
        migrations.AddField(
            model_name='about',
            name='about_description',
            field=models.TextField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
